---
version: '2.0'
services:
  recursor:
    image: powerdns/pdns-recursor-master
    environment:
      - PDNS_RECURSOR_API_KEY
    ports:
      - "2053:53"
      - "2053:53/udp"
      - "8082:8082"

  dnsdist:
    image: powerdns/dnsdist-master
    environment:
      - DNSDIST_API_KEY
    links:
      - recursor
      - auth
    ports:
      - "3053:53"
      - "3053:53/udp"
      - "5199:5199"
      - "8083:8083"

  auth:
    image: powerdns/pdns-auth-master
    environment:
      - PDNS_AUTH_API_KEY
    ports:
      - "1053:53"
      - "1053:53/udp"
      - "8081:8081"
